package pojo;
// Generated Oct 31, 2016 9:45:15 PM by Hibernate Tools 5.2.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BillDetail generated by hbm2java
 */
@Entity
@Table(name = "bill_detail")
public class BillDetail implements java.io.Serializable {

	private int billDetailId;
	private Bill bill;
	private Product product;
	private BigDecimal price;
	private Integer quantity;

	public BillDetail() {
	}

	public BillDetail(int billDetailId) {
		this.billDetailId = billDetailId;
	}

	public BillDetail(int billDetailId, Bill bill, Product product, BigDecimal price, Integer quantity) {
		this.billDetailId = billDetailId;
		this.bill = bill;
		this.product = product;
		this.price = price;
		this.quantity = quantity;
	}

	@Id

	@Column(name = "bill_detail_id", unique = true, nullable = false)
	public int getBillDetailId() {
		return this.billDetailId;
	}

	public void setBillDetailId(int billDetailId) {
		this.billDetailId = billDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bill_id")
	public Bill getBill() {
		return this.bill;
	}

	public void setBill(Bill bill) {
		this.bill = bill;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "price", precision = 18)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

}
