package pojo;
// Generated Oct 31, 2016 9:45:15 PM by Hibernate Tools 5.2.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bill generated by hbm2java
 */
@Entity
@Table(name = "bill")
public class Bill implements java.io.Serializable {

	private String billId;
	private Users users;
	private BigDecimal total;
	private String payment;
	private String address;
	private String date;
	private Set<BillDetail> billDetails = new HashSet<BillDetail>(0);

	public Bill() {
	}

	public Bill(String billId) {
		this.billId = billId;
	}

	public Bill(String billId, Users users, BigDecimal total, String payment, String address, String date,
			Set<BillDetail> billDetails) {
		this.billId = billId;
		this.users = users;
		this.total = total;
		this.payment = payment;
		this.address = address;
		this.date = date;
		this.billDetails = billDetails;
	}

	@Id

	@Column(name = "bill_id", unique = true, nullable = false)
	public String getBillId() {
		return this.billId;
	}

	public void setBillId(String billId) {
		this.billId = billId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "total", precision = 18)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@Column(name = "payment", length = 225)
	public String getPayment() {
		return this.payment;
	}

	public void setPayment(String payment) {
		this.payment = payment;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "date")
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bill")
	public Set<BillDetail> getBillDetails() {
		return this.billDetails;
	}

	public void setBillDetails(Set<BillDetail> billDetails) {
		this.billDetails = billDetails;
	}

}
