package pojo;
// Generated Oct 31, 2016 9:45:15 PM by Hibernate Tools 5.2.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product")
public class Product implements java.io.Serializable {

	private int productId;
	private Category category;
	private String productName;
	private String productImage;
	private BigDecimal productImportPrice;
	private BigDecimal productPrice;
	private String productDescription;
	private Set<BillDetail> billDetails = new HashSet<BillDetail>(0);

	public Product() {
	}

	public Product(int productId) {
		this.productId = productId;
	}

	public Product(int productId, Category category, String productName, String productImage,BigDecimal productImportPrice,
			BigDecimal productPrice, String productDescription) {
		this.productId = productId;
		this.category = category;
		this.productName = productName;
		this.productImage = productImage;
		this.productImportPrice=productImportPrice;
		this.productPrice = productPrice;
		this.productDescription = productDescription;

	}
	
	public Product(int productId, Category category, String productName, String productImage,BigDecimal productImportPrice,
			BigDecimal productPrice, String productDescription, Set<BillDetail> billDetails) {
		this.productId = productId;
		this.category = category;
		this.productName = productName;
		this.productImage = productImage;
		this.productImportPrice=productImportPrice;
		this.productPrice = productPrice;
		this.productDescription = productDescription;
		this.billDetails = billDetails;
	}

	@Id

	@Column(name = "product_id", unique = true, nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "product_name")
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "product_image")
	public String getProductImage() {
		return this.productImage;
	}

	public void setProductImage(String productImage) {
		this.productImage = productImage;
	}
	
	@Column(name = "product_importPrice", precision = 18)
	public BigDecimal getProductImportPrice() {
		return productImportPrice;
	}

	public void setProductImportPrice(BigDecimal productImportPrice) {
		this.productImportPrice = productImportPrice;
	}

	@Column(name = "product_price", precision = 18)
	public BigDecimal getProductPrice() {
		return this.productPrice;
	}

	public void setProductPrice(BigDecimal productPrice) {
		this.productPrice = productPrice;
	}

	@Column(name = "product_description")
	public String getProductDescription() {
		return this.productDescription;
	}

	public void setProductDescription(String productDescription) {
		this.productDescription = productDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<BillDetail> getBillDetails() {
		return this.billDetails;
	}

	public void setBillDetails(Set<BillDetail> billDetails) {
		this.billDetails = billDetails;
	}

}
