package pojo;
// Generated Oct 31, 2016 9:45:15 PM by Hibernate Tools 5.2.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users")
public class Users implements java.io.Serializable {

	private int userId;
	private String userEmail;
	private String userPass;
	private String userName;
	private Boolean userRole;
	private Set<Bill> bills = new HashSet<Bill>(0);

	public Users() {
	}

	public Users(int userId, String userEmail, String userPass, String userName) {
		this.userId = userId;
		this.userEmail = userEmail;
		this.userPass = userPass;
		this.userName = userName;
	}

	public Users(int userId, String userEmail, String userPass, String userName, Boolean userRole,
			Set<Bill> bills) {
		this.userId = userId;
		this.userEmail = userEmail;
		this.userPass = userPass;
		this.userName = userName;
		this.userRole = userRole;
		this.bills = bills;
	}

	@Id

	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "user_email", nullable = false)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "user_pass", nullable = false)
	public String getUserPass() {
		return this.userPass;
	}

	public void setUserPass(String userPass) {
		this.userPass = userPass;
	}

	@Column(name = "user_name", nullable = false)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_role")
	public Boolean getUserRole() {
		return this.userRole;
	}

	public void setUserRole(Boolean userRole) {
		this.userRole = userRole;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Bill> getBills() {
		return this.bills;
	}

	public void setBills(Set<Bill> bills) {
		this.bills = bills;
	}

}
